# Generated by Django 4.1 on 2022-10-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMascota', '0002_articulo_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
