# Generated by Django 4.1 on 2022-10-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMascota', '0006_remove_articulo_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
